### ISSUE TITLE
WS2812b led strip flicker

### ISSUE THREAD

**Issue by shaq80** [SciLor/ESP8266_Hyperion_LED-Controller#14]
WS2812b led strip flicker/flashes towards the end of the strip.

solved by adding:
#define FASTLED_ALLOW_INTERRUPTS 0 to the line immediately before #include <FastLED.h>
in WrapperFastLed.h

reference:
https://github.com/FastLED/FastLED/issues/306

**Comment by SciLor** [comment]
Could you try to add this define in the ConfigStatic.h 
This would be the best place to add that.
I would place it in the example Config then

**Comment by shaq80** [comment]
I will try that later this evening/tomorow and get back to you with result.

**Comment by shaq80** [comment]
i have added in ConfigStatic.h
#define FASTLED_ALLOW_INTERRUPTS 0
bellow #define CONFIG_LED_CLOCKLESS_CHIPSET WS2812B

it is working normal without flickering

**Comment by SciLor** [comment]
Added it in
#15 
Thank you!
