### ISSUE TITLE
Add relay

### ISSUE THREAD

**Issue by begicj** [SciLor/ESP8266_Hyperion_LED-Controller#29]
Can You add a relay that is activated when the LED strip lights up, and goes off 1 minute after the LED strip is off?

**Comment by SciLor** [comment]
What do you exactly mean?

**Comment by begicj** [comment]
I wonder if it is possible to add the possibility that the RELAY that is connected to the ESP8266 automatically goes ON when the led strip lights up, lets say if the STATIC mode or UDP mode is ON and there is some colors on LED strip?

If UDP mode or STATIC mode activates the black color (or FastLED.clear command), and there is no light on LED strip for 1 minute, that the relay automatically goes OFF and remains OFF until the udp or static mode activates any color of the LED strip?

**Comment by SciLor** [comment]
I don't understand you. What do you mean with "relay"?

**Comment by begicj** [comment]
![index](https://user-images.githubusercontent.com/24259043/37302687-8aa3c854-262c-11e8-96bb-c0293e8506d3.jpg)

It will be used to switch ON ambient lamp (220 V) behind armchair when ESP8266 lights LED strip....

**Comment by SciLor** [comment]
Sorry, that's not fitting in the project. You could easily implement it yourself, by adding code for switching your relay here:

[HyperionRGB.ino](https://github.com/SciLor/ESP8266_Hyperion_LED-Controller/blob/master/HyperionRGB/HyperionRGB.ino)

check out the chamgeMode function.
