### ISSUE TITLE
Run Hyperion only in one instance

### ISSUE THREAD

**Issue by DaPeace** [SciLor/ESP8266_Hyperion_LED-Controller#42]
Is it possible to use hyperion only in one instance and forward the data to the esp8266 or is the second instance a MUST?

**Comment by SciLor** [comment]
This is a hyperion related question, but you can easily use it with a single instance as primary output device
Just configurate hyperion as you would do it for a single instance and adjust the device configuration as described in the tutorials.

`{
      "colorOrder" : "rgb",
      "maxpacket" : 1450,
      "name" : "AmbiSZ-ESP8266",
      "output" : "ESP8266:19446", ///
      "protocol" : 0,
      "rate" : 250000,
      "type" : "udp"
},`

**Comment by DaPeace** [comment]
Thanks for the quick answer. Will try that in the afternoon!

**Comment by DaPeace** [comment]
Hello SciLor, ive tried out now. One instance is working BUT i have 2 problems.
First: Is it possible that the Serial Links from my old arduino-mini is much quicker than the wifi?
Second: My colors dont really match. Ive tried with 6 ws2812b leds on a small strip and that seems to be ok. But when i enable 122 leds that are mounted to my tv-backside the colors are mostly green and it does not really look like if it is analyzing the picture on the screen.

Regards, Jan

**Comment by SciLor** [comment]
I am using it for 300 leds without any problem. You should check if the wifi connection ist strong enough. 
The color problem should be a problem with a wrong configuration. Please check the hyperion forum for that. Maybe the color order ist wrong.

**Comment by DaPeace** [comment]
Yesterday i tried again without any luck. A small strip with 6 leds works but the 122 dont. Could it be that its not possible to drive the ws2812b-strip with 122 LEDS with the 3.3v-pins from the nodemcu?

**Comment by SciLor** [comment]
You can drive as much leds you want to. You just need a fitting power delivery.
Please try the rainbow effects without hyperion itself. Sometimes there are problems driving the leds without a 5V converter for the led pins.

**Comment by SciLor** [comment]
Better description see @https://github.com/SciLor/Hyperion_LED-Controller/commit/70adf21fd85af96dcd7423bb2cf44de30cd0cdfb

**Comment by andrein81** [comment]
sorry for the silly question. How do you guys run 2 instances of hyperion?
