### ISSUE TITLE
frequent wifi reconnects (spamming router logs)

### ISSUE THREAD

**Issue by nopnop9090** [SciLor/ESP8266_Hyperion_LED-Controller#45]
the esp8266 frequently loses connection and reconnects to wifi AP if idle and thus spamming routers logs:

`daemon.info hostapd: wlan1: STA xx:xx:xx:xx:7b:8c IEEE 802.11: disassociated
daemon.info hostapd: wlan1: STA xx:xx:xx:xx:7b:8c IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
daemon.info hostapd: wlan1: STA xx:xx:xx:xx:7b:8c IEEE 802.11: authenticated
daemon.info hostapd: wlan1: STA xx:xx:xx:xx:7b:8c IEEE 802.11: associated (aid 2)
daemon.notice hostapd: wlan1: AP-STA-CONNECTED xx:xx:xx:xx:7b:8c
daemon.info hostapd: wlan1: STA xx:xx:xx:xx:7b:8c WPA: pairwise key handshake completed (RSN)`

the solution that worked without much thinking about it:

add Esp8266-ping library, then put

**#include <Pinger.h>
Pinger pinger;**

to the top of HyperionRGB.ino

and 

**pinger.Ping(WiFi.gatewayIP());** 

to the void statusInfo(void) {} function (just before the last } bracket).

**Comment by SciLor** [comment]
This is no bug I think, this is the energy saving mode of the ESP8266. The same should happen with any Android or iOS device
