### ISSUE TITLE
Compiling process error message: "Compilation error: expected unqualified-id before '(' to"

### ISSUE THREAD

**Issue by emilwojcik93** [SciLor/ESP8266_Hyperion_LED-Controller#69]
Hi, when I tried to compile sketch via Arduino IDE. I received [error message](https://pastebin.com/DfvT919a)

I was tried to use latest version libs and those [specified in README.md](https://github.com/SciLor/Hyperion_LED-Controller/blob/master/README.md#libraries)

Error highlight [line 8 of BaseHeader.h](https://github.com/SciLor/Hyperion_LED-Controller/blob/master/HyperionRGB/BaseHeader.h#L8)

My [ConfigStatic.h file](https://pastebin.com/VxfPkBTP).

Please for help or fix.
Best regards.

**Comment by SciLor** [comment]
Which Arduino version and which board version did you use? Looks like you used board lib 3.1.1

**Comment by emilwojcik93** [comment]
Hi, sorry my fault, I miss this. Everything working fine, thank you for help :)
